import "./EnergyWaveObject.js"
class PulseEmitterComponent extends Component{
    name = "PulseEmitterComponent"
    start(){
        this.pulseFrequency = 50
        this.pulseTimer = 0
        this.pulseDamage = 0
        this.pulseLifespan = 25
        this.pulseRadius = 125
        this.upgrades = [
            {isAvaliable:true,weaponType:"emitter",upgradeType:"Damage",upgradeValue:10,upgradeName:"Damage++",upgradeDescription:"Adds a flat 10 damage to the pulse wave"},
            {isAvaliable:true,weaponType:"emitter",upgradeType:"Frequency",upgradeValue:0.1,upgradeName:"Frequency++",upgradeDescription:"Increases the frequency at which pulse waves are generated by 10%"},
            {isAvaliable:true,weaponType:"emitter",upgradeType:"Radius",upgradeValue:0.1,upgradeName:"Radius++",upgradeDescription:"Increases the maximum radius of the pulse wave by 10%"},
            {isAvaliable:true,weaponType:"emitter",upgradeType:"Lifespan",upgradeValue:0.1,upgradeName:"Lifespan++",upgradeDescrption:"Increases the lifespan of the pulse wave by 10%"}
        ]
        this.send(this,GameObject.getObjectByName("PlayerObject").components[4],"SendUpgrades")

    }
    update(){
        this.pulseTimer++
        if(this.pulseTimer >= this.pulseFrequency){
            GameObject.instantiate(new EnergyWaveObject(this.pulseDamage,this.pulseLifespan,this.pulseRadius))
            this.pulseTimer = 0
        }
        

    }
}
window.PulseEmitterComponent = PulseEmitterComponent